<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Hello</name>
   <tag></tag>
   <elementGuidId>7bc39f8f-44d1-472f-bc3f-1ca09ebdf814</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.banner-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Thúy Liễu xin chào 😊&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>4f2f493e-e72d-4b27-a7fd-6969e82989a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>banner-title</value>
      <webElementGuid>37f1819e-9728-48cc-9e82-75e28594ab36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thúy Liễu xin chào 😊</value>
      <webElementGuid>d306a9aa-5ae0-4d30-9d96-48bccdfcb185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;home-container&quot;]/div[@class=&quot;banner&quot;]/h1[@class=&quot;banner-title&quot;]</value>
      <webElementGuid>6d017ebf-f8e3-47c9-b1a6-24d332d4b136</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/h1</value>
      <webElementGuid>8bd24374-d08c-442d-a11a-03fb5b794610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng Nhập'])[1]/preceding::h1[1]</value>
      <webElementGuid>d30062e6-d37f-4050-a5a1-2372db02f6fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thúy Liễu xin chào']/parent::*</value>
      <webElementGuid>38c2d5ea-33a7-4e54-bb00-a1992b36e760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>7e7da3d2-b870-4759-8a86-64dfc72a9783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Thúy Liễu xin chào 😊' or . = 'Thúy Liễu xin chào 😊')]</value>
      <webElementGuid>99f2f742-d5da-4790-ad02-913b562427a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
