<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Welcome</name>
   <tag></tag>
   <elementGuidId>9721aae1-f41d-4761-9568-7ec94548e8a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.banner-subtitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Chào mừng bạn đến với ứng dụng của chúng tôi&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9c54b188-2f88-4336-820a-701423a333ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>banner-subtitle</value>
      <webElementGuid>335c71b4-ecee-4373-91f5-6708534cf9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chào mừng bạn đến với ứng dụng của chúng tôi</value>
      <webElementGuid>53c94151-1cce-4b61-88e9-6e6988c466e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;home-container&quot;]/div[@class=&quot;banner&quot;]/p[@class=&quot;banner-subtitle&quot;]</value>
      <webElementGuid>06f33d38-1ff3-4b90-b47b-4da2d3853dba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/p</value>
      <webElementGuid>f7692a34-f352-4fa7-8068-1c40c0951555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='😊'])[1]/following::p[1]</value>
      <webElementGuid>4a0f72a8-edc4-46ce-8e90-1df73bb664c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng Nhập'])[1]/preceding::p[1]</value>
      <webElementGuid>8889ea19-2819-463a-a6d3-1e857c39982d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng Ký'])[1]/preceding::p[1]</value>
      <webElementGuid>fee60e6d-fe13-4fbd-a747-3f17d8f10341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Chào mừng bạn đến với ứng dụng của chúng tôi']/parent::*</value>
      <webElementGuid>240c87b1-73df-4e83-b3c6-c65672280527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>2d60f50c-830f-437e-856e-667fc0056943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Chào mừng bạn đến với ứng dụng của chúng tôi' or . = 'Chào mừng bạn đến với ứng dụng của chúng tôi')]</value>
      <webElementGuid>68f1b6bc-d863-40aa-b4dd-4a408c711472</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
