<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>card_Login</name>
   <tag></tag>
   <elementGuidId>822b2cf1-b749-4930-9c68-30ebdf956961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.login-card</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Đăng NhậpEmail:Mật Khẩu:Đăng NhậpChưa có tài khoản? Đăng ký ngay&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab87942f-7113-4e30-afd0-dcfb3e5bbbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-card</value>
      <webElementGuid>d2a4df97-9c0b-4922-b194-084ef368d2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng NhậpEmail:Mật Khẩu:Đăng NhậpChưa có tài khoản? Đăng ký ngay</value>
      <webElementGuid>44ef4161-3caf-4a15-81ea-3f2f0c31b0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;login-container&quot;]/div[@class=&quot;login-card&quot;]</value>
      <webElementGuid>e4c7c5b7-b321-469f-9eb7-551ffc0bc589</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div</value>
      <webElementGuid>1863e972-9e08-4290-b5e2-ae7bea61dfce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>e864b7cc-1987-4320-9ed5-f3bd3e6d35e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Đăng NhậpEmail:Mật Khẩu:Đăng NhậpChưa có tài khoản? Đăng ký ngay' or . = 'Đăng NhậpEmail:Mật Khẩu:Đăng NhậpChưa có tài khoản? Đăng ký ngay')]</value>
      <webElementGuid>86cd573e-5bd9-4922-8fad-701c1665aaf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
