<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>card_profile</name>
   <tag></tag>
   <elementGuidId>177d5298-b28f-4c52-8657-8747e8d0ae16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.profile-card</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Thông Tin Cá Nhân✏️ Chỉnh SửaTên Đầy Đủ:liuEmail:liu@abc.comGiới Tính:NữKỹ Năng:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dfdbfa4e-bf4a-4dc5-b571-a927168f1042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile-card</value>
      <webElementGuid>c3f6f029-a614-474c-86c7-5d0859f60d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thông Tin Cá Nhân✏️ Chỉnh SửaTên Đầy Đủ:liuEmail:liu@abc.comGiới Tính:NữKỹ Năng:-Ngày Đăng Ký:🔐 Thay Đổi Mật Khẩu</value>
      <webElementGuid>5b47ac58-dde6-4069-bc15-d9e4f6cd3176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;profile-container&quot;]/div[@class=&quot;profile-card&quot;]</value>
      <webElementGuid>5f24fffd-a641-4348-83ac-2d5b252ca8cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div</value>
      <webElementGuid>3454a9cd-5d7a-417a-ae54-bd7f050d2734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>aa4b7f16-fed5-4d77-9461-9898f402b537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Thông Tin Cá Nhân✏️ Chỉnh SửaTên Đầy Đủ:liuEmail:liu@abc.comGiới Tính:NữKỹ Năng:-Ngày Đăng Ký:🔐 Thay Đổi Mật Khẩu' or . = 'Thông Tin Cá Nhân✏️ Chỉnh SửaTên Đầy Đủ:liuEmail:liu@abc.comGiới Tính:NữKỹ Năng:-Ngày Đăng Ký:🔐 Thay Đổi Mật Khẩu')]</value>
      <webElementGuid>61a4bd3e-9f0e-4a5d-a2a5-3162622ed5d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
