<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>card_Register</name>
   <tag></tag>
   <elementGuidId>8f5cf4fb-cca7-4850-8011-262cc08fb153</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.signup-card</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Đăng Ký Tài KhoảnTên Đầy Đủ:Email:Mật Khẩu:Xác Nhận Mật Khẩu:Giới Tính:NamNữKỹ N&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8f0969b4-2909-4515-8258-ff5a4ba4b6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signup-card</value>
      <webElementGuid>bfab6d55-d0a8-4d03-a67e-fed203fb1780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng Ký Tài KhoảnTên Đầy Đủ:Email:Mật Khẩu:Xác Nhận Mật Khẩu:Giới Tính:NamNữKỹ Năng:HátMúaRapKịchĐăng KýĐã có tài khoản? Đăng nhập ngay</value>
      <webElementGuid>04589704-7644-4547-8c22-40e4cea12a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;signup-container&quot;]/div[@class=&quot;signup-card&quot;]</value>
      <webElementGuid>4f8a1101-b65a-4023-ae66-c308e7768e00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div</value>
      <webElementGuid>cd07d612-4325-4103-ba54-d1d3df17ad02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>a1756b60-e8b1-4043-afb7-c4168cdead05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Đăng Ký Tài KhoảnTên Đầy Đủ:Email:Mật Khẩu:Xác Nhận Mật Khẩu:Giới Tính:NamNữKỹ Năng:HátMúaRapKịchĐăng KýĐã có tài khoản? Đăng nhập ngay' or . = 'Đăng Ký Tài KhoảnTên Đầy Đủ:Email:Mật Khẩu:Xác Nhận Mật Khẩu:Giới Tính:NamNữKỹ Năng:HátMúaRapKịchĐăng KýĐã có tài khoản? Đăng nhập ngay')]</value>
      <webElementGuid>a6396aba-5fd3-439a-89a6-71ec0ea7fe1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
