<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gender</name>
   <tag></tag>
   <elementGuidId>3471ae34-8d4a-49f3-bf68-8561de01b3b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/form/div[5]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.radio-group</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;NamNữ&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e74092bf-d314-410c-8c14-77789f539158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-group</value>
      <webElementGuid>59df9f16-cc31-4906-a250-a1beace21423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NamNữ</value>
      <webElementGuid>45bb9992-98c2-461e-8a6a-b594ad8cf610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;signup-container&quot;]/div[@class=&quot;signup-card&quot;]/form[1]/div[@class=&quot;form-group&quot;]/div[@class=&quot;radio-group&quot;]</value>
      <webElementGuid>adf8979b-9845-45a8-a119-6a458141466a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div[5]/div</value>
      <webElementGuid>5993b521-2e17-4265-bbf2-10fbc1bfc506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giới Tính:'])[1]/following::div[1]</value>
      <webElementGuid>d059de03-725b-4cee-9a6c-d1d8df3a1320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xác Nhận Mật Khẩu:'])[1]/following::div[3]</value>
      <webElementGuid>5d92805c-1775-4335-925b-7905e38c40e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div</value>
      <webElementGuid>fb56cb38-5451-43e7-a2f7-d6b3030134cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'NamNữ' or . = 'NamNữ')]</value>
      <webElementGuid>345a69f6-d043-42fa-a6ec-a156efcb84fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
