<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>opt_skill</name>
   <tag></tag>
   <elementGuidId>4f95e444-2cd3-4e98-af54-3cc0df3e60e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/form/div[6]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.checkbox-group</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;HátMúaRapKịch&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>82fbb8b3-00d3-42c4-8717-1917b5ab227d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-group</value>
      <webElementGuid>469dcf1c-8821-4936-bcd3-0d3f1c4abc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HátMúaRapKịch</value>
      <webElementGuid>c0cf369a-b79c-40b5-b6fb-ba460d4dccbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;signup-container&quot;]/div[@class=&quot;signup-card&quot;]/form[1]/div[@class=&quot;form-group&quot;]/div[@class=&quot;checkbox-group&quot;]</value>
      <webElementGuid>e1271bfb-6fa1-4dce-810e-ab8dfc82ed5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/div[6]/div</value>
      <webElementGuid>070f0252-060c-4db8-9395-f5a148cc1b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kỹ Năng:'])[1]/following::div[1]</value>
      <webElementGuid>dc3aae4c-d29f-45df-bc67-b1b842090228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nữ'])[1]/following::div[2]</value>
      <webElementGuid>a1a4d8b1-6225-434a-9918-dd691a1a67f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>d23e6469-0651-4711-a606-e43c049aafde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'HátMúaRapKịch' or . = 'HátMúaRapKịch')]</value>
      <webElementGuid>1b0f4792-71d7-48de-8350-e8883e581940</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
